### ISSUE TITLE
st

### ISSUE THREAD

**Issue by holyknight113** [nftstorage/nft.storage-tools#3]
Hi there,

I'm testing the import.js and got this error :  

node .\import .\test3.txt

Internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from C:\Users\Ghost\Desktop\CryptoSeed\importnftstorage\nft.storage-tools\import.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'

Any idea where stream is ?

**Comment by dchoi27** [comment]
Hey there - what version of Node are you using? We'd recommend using the latest version.

**Comment by alanshaw** [comment]
`stream` is an internal node module. Maybe there is some bundling going on here? If yes then you'll probably need to ensure node.js builtins are available in the bundle...these tools are meant for running on the command line though so YMMV.

Please re-open if you still have an issue.
